
try { 
    divisione()
    
} catch (error) {
     alert("il  risultato non e diverse da zero");
};
